### ISSUE TITLE
Build on linux fails

### ISSUE THREAD

**Issue by aylen384** [csete/qthid#15]
The build on linux fails atm.

This patch will fix that: http://pastebin.com/jzfXBuG9

**Comment by csete** [comment]
Which branch are you referring to? We switched from libusb to udev because of problems with libusb-1.0.9. Maybe build fails for you because you don't have libudev-dev installed?

**Comment by aylen384** [comment]
I'm building qthid-3.0

And (at least last time I tried) the build using qtcreator succeded, but qmake didn't.
For packaging we cannot rely on qtcreator.

I will have a look at my system and tell you if the the libudev-dev files were installed - but I do think so as Archlinux doesn't have seperate devel pkg's.

**Comment by aylen384** [comment]
It seems to work without any patch using version 3.2
