### ISSUE TITLE
Wrong command used in on_doubleSpinBoxPhase_valueChanged?

### ISSUE THREAD

**Issue by kabunkie** [csete/qthid#5]
void MainWindow::on_doubleSpinBoxPhase_valueChanged(double value)
{
...
    fcdAppSetParam(FCD_CMD_APP_SET_DC_CORR, iqinfo.auc, 4);
}

Shouldn't this be done using 'FCD_CMD_APP_SET_IQ_CORR' instead of 'FCD_CMD_APP_SET_DC_CORR'?

**Comment by csete** [comment]
Indeed, it should be FCD_CMD_APP_SET_IQ_CORR. Thanks.

**Comment by csete** [comment]
Use correct FCD command to set IQ Phase correction. Thanks to @kabunkie. Closed by 8682b37ece5283fbbdbacb63784e7b5f69b7bfd5
